// <auto-generated />
namespace On_Call_Assistant.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class EmpVacHours : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EmpVacHours));
        
        string IMigrationMetadata.Id
        {
            get { return "201504062052090_EmpVacHours"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
